import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _locale = const Locale('pt');

  Locale get locale => _locale;

  LanguageProvider() {
    // Padrão sempre em português independente do idioma do dispositivo
    _locale = const Locale('pt');
  }

  void setLocale(Locale locale) {
    if (!['pt', 'en', 'es'].contains(locale.languageCode)) return;
    _locale = locale;
    notifyListeners();
  }
}

class AppStrings {
  static final Map<String, Map<String, String>> _localizedValues = {
    'pt': {
      'tabHome': 'Início',
      'tabHistory': 'Histórico',
      'tabProfile': 'Perfil',
      'editProfile': 'Editar Perfil',
      'notifications': 'Notificações',
      'language': 'Idioma',
      'theme': 'Tema',
      'helpSupport': 'Ajuda e Suporte',
      'contactUs': 'Fale Conosco',
      'privacyPolicy': 'Política de Privacidade',
      'logout': 'Sair',
      'portuguese': 'Português',
      'english': 'Inglês',
      'spanish': 'Espanhol',
      'dark': 'Escuro',
      'light': 'Claro',
      'save': 'Salvar',
      'name': 'Nome Completo',
      'email': 'E-mail',
      'phone': 'Telefone',
      'profileUpdated': 'Perfil atualizado com sucesso!',
      'enterName': 'Por favor, insira seu nome',
      'enterEmail': 'Por favor, insira seu e-mail',
      'invalidEmail': 'E-mail inválido',
      'enterPhone': 'Por favor, insira seu telefone',
      'general': 'Geral',
      'receiveNotifications': 'Receber Notificações',
      'receiveNotificationsSub': 'Ativar ou desativar todas as notificações do app',
      'categories': 'Categorias',
      'newEvents': 'Novos Eventos',
      'newEventsSub': 'Palestras, workshops e reuniões',
      'scheduleChanges': 'Alterações de Horário',
      'scheduleChangesSub': 'Mudanças em aulas e cronogramas',
      'documents': 'Documentos Publicados',
      'documentsSub': 'Atas, pautas e regulamentos',
      'announcements': 'Avisos da Coordenação',
      'announcementsSub': 'Comunicados importantes do campus',
      'channels': 'Canais de Recebimento',
      'pushNotifications': 'Push Notifications',
      'pushNotificationsSub': 'Alertas no dispositivo',
      'emailSub': 'Resumo diário de atividades',
      'selectLanguage': 'Selecione o Idioma',
      'locationsTitle': 'Locais',
      'manageCategories': 'Gerenciar Categorias',
      'manage': 'Gerenciar',
      'newPlace': 'Novo Local',
      'placeName': 'Nome do Local',
      'address': 'Endereço',
      'cancel': 'Cancelar',
      'editPlace': 'Editar Local',
      'noPlaces': 'Nenhum local cadastrado',
      'categoryLodgingTitle': 'Hospedagem',
      'categoryLodgingSubtitle': 'Hotéis e Pousadas',
      'categoryFoodTitle': 'Alimentação',
      'categoryFoodSubtitle': 'Restaurantes e Cafés',
      'categoryEventTitle': 'O Evento',
      'categoryEventSubtitle': 'Auditórios e Salas',
      'categoryTransportTitle': 'Transporte',
      'categoryTransportSubtitle': 'Ônibus e Táxis',
      'categoryTourismTitle': 'Turismo',
      'categoryTourismSubtitle': 'Pontos turísticos da cidade',
      'categoryHealthTitle': 'Saúde',
      'categoryHealthSubtitle': 'Hospitais e Farmácias',
      'documentsTitle': 'Documentos',
      'meetingFiles': 'Arquivos da Reunião',
      'meetingFilesSubtitle': 'Acesse as pautas, atas e materiais complementares.',
      'downloadingFile': 'Baixando arquivo...',
      'eventCaxiasMeeting': 'Reunião Campus Caxias',
      'join': 'Participar',
      'startsIn': 'Começa em',
      'viewSchedule': 'Cronograma',
      'presenceConfirmed': 'Presença confirmada com sucesso!',
      'confirmPresence': 'Confirmar presença',
      'presenceConfirmedLabel': '✓ Presença Confirmada',
      'locationsShort': 'Locais',
      'documentsShort': 'Docs',
      'schedule': 'Cronograma',
      'scheduleLocation': 'Auditório Principal',
      'scheduleDate': '12 de Dezembro de 2025',
      'checkinCoffee': 'Credenciamento e Café',
      'checkinCoffeeDesc': 'Recepção dos participantes e entrega de material.',
      'openingSession': 'Abertura Oficial',
      'openingSessionDesc': 'Palavra do Diretor Geral e convidados.',
      'roundTable': 'Mesa Redonda: Inovação',
      'roundTableDesc': 'Debate sobre novas tecnologias no campus.',
      'lunchBreak': 'Intervalo para Almoço',
      'lunchBreakDesc': 'Livre para almoço.',
      'workshops': 'Workshops Práticos',
      'workshopsDesc': 'Salas temáticas (TI, Agronomia, Administração).',
      'closingSession': 'Encerramento',
      'closingSessionDesc': 'Coffee break e networking.',
      'historyTitle': 'Histórico',
      'filterAll': 'Todos',
      'filterInProgress': 'Em Andamento',
      'filterCompleted': 'Finalizado',
      'filterAbsent': 'Ausente',
      'searchHint': 'Pesquisar evento...',
      'statusInProgress': 'Em Andamento',
      'statusCompleted': 'Finalizado',
      'statusAbsent': 'Ausente',
      'detailsTitle': 'Detalhes',
      'certificateButton': 'Certificado',
      'completionDate': 'Data de Conclusão:',
      'meetingDocuments': 'Documentos de Reunião',
      'contactHeading': 'Entre em contato',
      'contactDescription': 'Estamos aqui para ajudar. Escolha uma das formas abaixo para falar com a gente.',
      'emailLabel': 'E-mail',
      'phoneLabel': 'Telefone',
      'addressLabel': 'Endereço',
      'socialNetworks': 'Redes Sociais',
      'faqTitle': 'Perguntas Frequentes',
      'faqChangePasswordQ': 'Como altero minha senha?',
      'faqChangePasswordA': 'Para alterar sua senha, vá até "Editar Perfil" e selecione a opção de segurança.',
      'faqSeeSchedulesQ': 'Onde vejo os horários das aulas?',
      'faqSeeSchedulesA': 'Os horários estão disponíveis na aba "Horários" na tela inicial.',
      'faqContactCoordinationQ': 'Como entro em contato com a coordenação?',
      'faqContactCoordinationA': 'Você pode usar a tela "Fale Conosco" para encontrar os contatos oficiais.',
      'faqOfflineQ': 'O aplicativo funciona offline?',
      'faqOfflineA': 'Algumas funcionalidades requerem internet, mas o histórico de notificações pode ser visto offline.',
      'fillRequiredFields': 'Preencha todos os campos obrigatórios.',
      'needInstitutionalEmail': 'É necessário usar o email institucional!',
      'login': 'Entrar',
      'noAccount': 'Não tem uma conta?',
      'register': 'Cadastre-se',
      'academicEmail': 'Email Acadêmico',
      'password': 'Senha',
      'rememberLogin': 'Lembrar login',
      'confirmPassword': 'Confirmar Senha',
      'registerAction': 'CADASTRAR',
      'passwordsDontMatch': 'As senhas não conferem!',
      'createAccount': 'Criar Conta',
      'emailHelper': 'Ex: usuario@acad.ifma.edu.br',
      'enterFullCode': 'Por favor, digite o código completo.',
      'accountVerified': 'Conta verificada com sucesso!',
      'serverConnectionError': 'Erro ao conectar com o servidor.',
      'verifyEmailTitle': 'Verifique seu E-mail',
      'codeSentTo': 'Enviamos um código de 6 dígitos para:',
      'verificationButton': 'VERIFICAR CÓDIGO',
      'resendCode': 'Não recebeu o código? Reenviar',
      'resendSoon': 'Função de reenviar em breve!',
      'lastUpdate': 'Última atualização: 27 de Dezembro de 2025',
      'privacyIntroTitle': 'Introdução',
      'privacyDataTitle': 'Coleta de Dados',
      'privacyUsageTitle': 'Uso das Informações',
      'privacySharingTitle': 'Compartilhamento',
      'privacySecurityTitle': 'Segurança',
      'privacyIntro': 'Bem-vindo ao aplicativo FADIR. Sua privacidade é importante para nós. Esta Política de Privacidade explica como coletamos, usamos, divulgamos e protegemos suas informações.',
      'privacyDataCollection': 'Coletamos informações que você nos fornece diretamente, como nome, e-mail e foto de perfil, para personalizar sua experiência no aplicativo.',
      'privacyUsage': 'Usamos suas informações para fornecer, manter e melhorar nossos serviços, além de enviar notificações importantes sobre o campus e eventos.',
      'privacySharing': 'Não compartilhamos suas informações pessoais com terceiros, exceto quando exigido por lei ou para proteger nossos direitos.',
      'privacySecurity': 'Implementamos medidas de segurança para proteger seus dados contra acesso não autorizado, alteração ou destruição.',
      'privacyFooter': 'FADIR - Campus Caxias',
      'error': 'Erro',
      'retry': 'Tentar novamente',
      'noPublications': 'Nenhuma publicação ainda.',
      'justNow': 'Agora mesmo',
      'minutesAgo': 'min atrás',
      'hoursAgo': 'h atrás',
      'daysAgo': 'dias atrás',
      'unknownDate': 'Data desconhecida',
      'logoNotFound': 'Logo não encontrada',
      'defaultUserName': 'Usuário FADIR',
      'createPost': 'Criar Publicação',
      'commentsTitle': 'Comentários',
      'commentsEmptyTitle': 'Ainda não há comentários',
      'commentsEmptySubtitle': 'Seja o primeiro a comentar.',
      'commentsListError': 'Não foi possível carregar os comentários.',
      'commentsRetry': 'Tentar novamente',
      'fabPost': 'Postar',
      'fabEdit': 'Editar',
      'createMeetingTitle': 'Criar Nova Reunião',
      'meetingEditTitle': 'Editar Reunião',
      'meetingGeneralData': 'Dados Gerais',
      'meetingName': 'Nome do Evento',
      'meetingCampus': 'Campus / Local',
      'meetingStartDate': 'Data de Início',
      'meetingEndDate': 'Data de Encerramento',
      'meetingSchedule': 'Cronograma',
      'meetingAddItem': 'Adicionar Item',
      'meetingSelectStartFirst': 'Selecione a data inicial primeiro!',
      'meetingEndBeforeStart': 'A data de término não pode ser antes do início!',
      'meetingAddActivity': 'Adicione pelo menos uma atividade!',
      'meetingSave': 'SALVAR REUNIÃO',
      'meetingUpdate': 'ATUALIZAR DADOS',
      'meetingCreateSuccess': 'Reunião criada com sucesso! ✅',
      'meetingUpdateSuccess': 'Reunião atualizada com sucesso! ✅',
      'requiredField': 'Obrigatório',
      'publish': 'Publicar',
      'postHint': 'O que você quer compartilhar?',
      'addToPost': 'Adicionar ao post',
      'addPhoto': 'Adicionar foto',
      'takePhoto': 'Tirar foto',
      'publicAudience': 'Público',
      'imageSelectError': 'Erro ao selecionar imagem',
      'publishSuccess': 'Publicado com sucesso!',
      'publishError': 'Erro ao publicar',
      'documentAgendaDecember': 'Pauta da Reunião - Dezembro',
      'documentResults2025': 'Apresentação de Resultados 2025',
      'documentBudget2026': 'Planilha de Orçamentos 2026',
      'documentPreviousMinutes': 'Ata da Reunião Anterior',
      'documentInternalRegulation': 'Regulamento Interno',
      'eventSaoJoaoMeeting': 'Reunião Campus São João dos Patos',
      'eventSaoLuisMeeting': 'Reunião Campus São Luís',
      'eventCodoMeeting': 'Reunião Campus Codó',
      'eventTimonMeeting': 'Reunião Campus Timon',
    },
    'en': {
      'tabHome': 'Home',
      'tabHistory': 'History',
      'tabProfile': 'Profile',
      'editProfile': 'Edit Profile',
      'notifications': 'Notifications',
      'language': 'Language',
      'theme': 'Theme',
      'helpSupport': 'Help & Support',
      'contactUs': 'Contact Us',
      'privacyPolicy': 'Privacy Policy',
      'logout': 'Logout',
      'portuguese': 'Portuguese',
      'english': 'English',
      'spanish': 'Spanish',
      'dark': 'Dark',
      'light': 'Light',
      'save': 'Save',
      'name': 'Full Name',
      'email': 'E-mail',
      'phone': 'Phone',
      'profileUpdated': 'Profile updated successfully!',
      'enterName': 'Please enter your name',
      'enterEmail': 'Please enter your email',
      'invalidEmail': 'Invalid email',
      'enterPhone': 'Please enter your phone number',
      'general': 'General',
      'receiveNotifications': 'Receive Notifications',
      'receiveNotificationsSub': 'Enable or disable all app notifications',
      'categories': 'Categories',
      'newEvents': 'New Events',
      'newEventsSub': 'Lectures, workshops and meetings',
      'scheduleChanges': 'Schedule Changes',
      'scheduleChangesSub': 'Changes in classes and schedules',
      'documents': 'Published Documents',
      'documentsSub': 'Minutes, agendas and regulations',
      'announcements': 'Coordination Announcements',
      'announcementsSub': 'Important campus announcements',
      'channels': 'Reception Channels',
      'pushNotifications': 'Push Notifications',
      'pushNotificationsSub': 'Device alerts',
      'emailSub': 'Daily activity summary',
      'selectLanguage': 'Select Language',
      'locationsTitle': 'Places',
      'manageCategories': 'Manage Categories',
      'manage': 'Manage',
      'newPlace': 'New Place',
      'placeName': 'Place Name',
      'address': 'Address',
      'cancel': 'Cancel',
      'editPlace': 'Edit Place',
      'noPlaces': 'No places registered',
      'categoryLodgingTitle': 'Lodging',
      'categoryLodgingSubtitle': 'Hotels and Inns',
      'categoryFoodTitle': 'Food',
      'categoryFoodSubtitle': 'Restaurants and Cafés',
      'categoryEventTitle': 'The Event',
      'categoryEventSubtitle': 'Auditoriums and Rooms',
      'categoryTransportTitle': 'Transport',
      'categoryTransportSubtitle': 'Buses and Taxis',
      'categoryTourismTitle': 'Tourism',
      'categoryTourismSubtitle': 'City attractions',
      'categoryHealthTitle': 'Health',
      'categoryHealthSubtitle': 'Hospitals and Pharmacies',
      'documentsTitle': 'Documents',
      'meetingFiles': 'Meeting Files',
      'meetingFilesSubtitle': 'Access agendas, minutes, and supporting material.',
      'downloadingFile': 'Downloading file...',
      'eventCaxiasMeeting': 'Caxias Campus Meeting',
      'join': 'Join',
      'startsIn': 'Starts in',
      'viewSchedule': 'Schedule',
      'presenceConfirmed': 'Attendance confirmed successfully!',
      'confirmPresence': 'Confirm presence',
      'presenceConfirmedLabel': '✓ Attendance Confirmed',
      'locationsShort': 'Places',
      'documentsShort': 'Docs',
      'schedule': 'Schedule',
      'scheduleLocation': 'Main Auditorium',
      'scheduleDate': 'December 12, 2025',
      'checkinCoffee': 'Check-in & Coffee',
      'checkinCoffeeDesc': 'Participant reception and materials.',
      'openingSession': 'Opening Ceremony',
      'openingSessionDesc': 'Remarks from the Director and guests.',
      'roundTable': 'Roundtable: Innovation',
      'roundTableDesc': 'Debate on new technologies on campus.',
      'lunchBreak': 'Lunch Break',
      'lunchBreakDesc': 'Free time for lunch.',
      'workshops': 'Hands-on Workshops',
      'workshopsDesc': 'Themed rooms (IT, Agronomy, Administration).',
      'closingSession': 'Closing',
      'closingSessionDesc': 'Coffee break and networking.',
      'historyTitle': 'History',
      'filterAll': 'All',
      'filterInProgress': 'In Progress',
      'filterCompleted': 'Completed',
      'filterAbsent': 'Absent',
      'searchHint': 'Search event...',
      'statusInProgress': 'In Progress',
      'statusCompleted': 'Completed',
      'statusAbsent': 'Absent',
      'detailsTitle': 'Details',
      'certificateButton': 'Certificate',
      'completionDate': 'Completion Date:',
      'meetingDocuments': 'Meeting Documents',
      'contactHeading': 'Get in touch',
      'contactDescription': 'We are here to help. Choose one of the options below to reach us.',
      'emailLabel': 'Email',
      'phoneLabel': 'Phone',
      'addressLabel': 'Address',
      'socialNetworks': 'Social Media',
      'faqTitle': 'Frequently Asked Questions',
      'faqChangePasswordQ': 'How do I change my password?',
      'faqChangePasswordA': 'To change your password, go to "Edit Profile" and choose the security option.',
      'faqSeeSchedulesQ': 'Where can I see class schedules?',
      'faqSeeSchedulesA': 'Schedules are available in the "Schedules" tab on the home screen.',
      'faqContactCoordinationQ': 'How do I contact the coordination office?',
      'faqContactCoordinationA': 'You can use the "Contact Us" screen to find the official contacts.',
      'faqOfflineQ': 'Does the app work offline?',
      'faqOfflineA': 'Some features require internet, but the notification history can be viewed offline.',
      'fillRequiredFields': 'Please fill in all required fields.',
      'needInstitutionalEmail': 'You must use the institutional email!',
      'login': 'Sign in',
      'noAccount': "Don't have an account?",
      'register': 'Sign up',
      'academicEmail': 'Academic Email',
      'password': 'Password',
      'rememberLogin': 'Remember login',
      'confirmPassword': 'Confirm Password',
      'registerAction': 'REGISTER',
      'passwordsDontMatch': 'Passwords do not match!',
      'createAccount': 'Create Account',
      'emailHelper': 'E.g.: user@acad.ifma.edu.br',
      'enterFullCode': 'Please enter the full code.',
      'accountVerified': 'Account verified successfully!',
      'serverConnectionError': 'Error connecting to the server.',
      'verifyEmailTitle': 'Check your email',
      'codeSentTo': 'We sent a 6-digit code to:',
      'verificationButton': 'VERIFY CODE',
      'resendCode': "Didn't receive the code? Resend",
      'resendSoon': 'Resend feature coming soon!',
      'lastUpdate': 'Last update: December 27, 2025',
      'privacyIntroTitle': 'Introduction',
      'privacyDataTitle': 'Data Collection',
      'privacyUsageTitle': 'Use of Information',
      'privacySharingTitle': 'Sharing',
      'privacySecurityTitle': 'Security',
      'privacyIntro': 'Welcome to the FADIR app. Your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and protect your information.',
      'privacyDataCollection': 'We collect information you provide directly, such as name, email, and profile photo, to personalize your experience in the app.',
      'privacyUsage': 'We use your information to provide, maintain, and improve our services, and to send important notifications about the campus and events.',
      'privacySharing': 'We do not share your personal information with third parties, except when required by law or to protect our rights.',
      'privacySecurity': 'We implement security measures to protect your data from unauthorized access, alteration, or destruction.',
      'privacyFooter': 'FADIR - Caxias Campus',
      'error': 'Error',
      'retry': 'Try again',
      'noPublications': 'No posts yet.',
      'justNow': 'Just now',
      'minutesAgo': 'min ago',
      'hoursAgo': 'h ago',
      'daysAgo': 'days ago',
      'unknownDate': 'Unknown date',
      'logoNotFound': 'Logo not found',
      'defaultUserName': 'FADIR User',
      'createPost': 'Create Post',
      'commentsTitle': 'Comments',
      'commentsEmptyTitle': 'No comments yet',
      'commentsEmptySubtitle': 'Be the first to comment.',
      'commentsListError': 'Could not load comments.',
      'commentsRetry': 'Try again',
      'fabPost': 'Post',
      'fabEdit': 'Edit',
      'createMeetingTitle': 'Create New Meeting',
      'meetingGeneralData': 'General Info',
      'meetingName': 'Event Name',
      'meetingCampus': 'Campus / Venue',
      'meetingStartDate': 'Start Date',
      'meetingEndDate': 'End Date',
      'meetingSchedule': 'Schedule',
      'meetingAddItem': 'Add Item',
      'meetingSelectStartFirst': 'Select the start date first!',
      'meetingEndBeforeStart': 'End date cannot be before start date!',
      'meetingAddActivity': 'Add at least one activity!',
      'meetingSave': 'SAVE MEETING',
      'meetingCreateSuccess': 'Meeting created successfully! ✅',
      'meetingEditTitle': 'Edit Meeting',
      'meetingUpdate': 'UPDATE MEETING',
      'meetingUpdateSuccess': 'Meeting updated successfully! ✅',
      'requiredField': 'Required',
      'publish': 'Publish',
      'postHint': 'What do you want to share?',
      'addToPost': 'Add to post',
      'addPhoto': 'Add photo',
      'takePhoto': 'Take photo',
      'publicAudience': 'Public',
      'imageSelectError': 'Error selecting image',
      'publishSuccess': 'Published successfully!',
      'publishError': 'Error while publishing',
      'documentAgendaDecember': 'Meeting Agenda - December',
      'documentResults2025': '2025 Results Presentation',
      'documentBudget2026': 'Budget Spreadsheet 2026',
      'documentPreviousMinutes': 'Previous Meeting Minutes',
      'documentInternalRegulation': 'Internal Regulation',
      'eventSaoJoaoMeeting': 'São João dos Patos Campus Meeting',
      'eventSaoLuisMeeting': 'São Luís Campus Meeting',
      'eventCodoMeeting': 'Codó Campus Meeting',
      'eventTimonMeeting': 'Timon Campus Meeting',
    },
    'es': {
      'tabHome': 'Inicio',
      'tabHistory': 'Historial',
      'tabProfile': 'Perfil',
      'editProfile': 'Editar perfil',
      'notifications': 'Notificaciones',
      'language': 'Idioma',
      'theme': 'Tema',
      'helpSupport': 'Ayuda y soporte',
      'contactUs': 'Contáctanos',
      'privacyPolicy': 'Política de privacidad',
      'logout': 'Cerrar sesión',
      'portuguese': 'Portugués',
      'english': 'Inglés',
      'spanish': 'Español',
      'dark': 'Oscuro',
      'light': 'Claro',
      'save': 'Guardar',
      'name': 'Nombre completo',
      'email': 'Correo electrónico',
      'phone': 'Teléfono',
      'profileUpdated': 'Perfil actualizado con éxito!',
      'enterName': 'Por favor, ingresa tu nombre',
      'enterEmail': 'Por favor, ingresa tu correo',
      'invalidEmail': 'Correo inválido',
      'enterPhone': 'Por favor, ingresa tu teléfono',
      'general': 'General',
      'receiveNotifications': 'Recibir notificaciones',
      'receiveNotificationsSub': 'Activar o desactivar todas las notificaciones de la app',
      'categories': 'Categorías',
      'newEvents': 'Nuevos eventos',
      'newEventsSub': 'Conferencias, talleres y reuniones',
      'scheduleChanges': 'Cambios de horario',
      'scheduleChangesSub': 'Cambios en clases y cronogramas',
      'documents': 'Documentos publicados',
      'documentsSub': 'Actas, agendas y reglamentos',
      'announcements': 'Avisos de la coordinación',
      'announcementsSub': 'Comunicados importantes del campus',
      'channels': 'Canales de recepción',
      'pushNotifications': 'Notificaciones push',
      'pushNotificationsSub': 'Alertas en el dispositivo',
      'emailSub': 'Resumen diario de actividades',
      'selectLanguage': 'Selecciona el idioma',
      'locationsTitle': 'Lugares',
      'manageCategories': 'Administrar categorías',
      'manage': 'Administrar',
      'newPlace': 'Nuevo lugar',
      'placeName': 'Nombre del lugar',
      'address': 'Dirección',
      'cancel': 'Cancelar',
      'editPlace': 'Editar lugar',
      'noPlaces': 'Ningún lugar registrado',
      'categoryLodgingTitle': 'Alojamiento',
      'categoryLodgingSubtitle': 'Hoteles y posadas',
      'categoryFoodTitle': 'Alimentación',
      'categoryFoodSubtitle': 'Restaurantes y cafés',
      'categoryEventTitle': 'El evento',
      'categoryEventSubtitle': 'Auditorios y salas',
      'categoryTransportTitle': 'Transporte',
      'categoryTransportSubtitle': 'Autobuses y taxis',
      'categoryTourismTitle': 'Turismo',
      'categoryTourismSubtitle': 'Puntos turísticos de la ciudad',
      'categoryHealthTitle': 'Salud',
      'categoryHealthSubtitle': 'Hospitales y farmacias',
      'documentsTitle': 'Documentos',
      'meetingFiles': 'Archivos de la reunión',
      'meetingFilesSubtitle': 'Accede a agendas, actas y materiales de apoyo.',
      'downloadingFile': 'Descargando archivo...',
      'eventCaxiasMeeting': 'Reunión Campus Caxias',
      'join': 'Participar',
      'startsIn': 'Comienza en',
      'viewSchedule': 'Cronograma',
      'presenceConfirmed': 'Asistencia confirmada con éxito!',
      'confirmPresence': 'Confirmar asistencia',
      'presenceConfirmedLabel': '✓ Asistencia confirmada',
      'locationsShort': 'Lugares',
      'documentsShort': 'Docs',
      'schedule': 'Cronograma',
      'scheduleLocation': 'Auditorio principal',
      'scheduleDate': '12 de diciembre de 2025',
      'checkinCoffee': 'Credencial y café',
      'checkinCoffeeDesc': 'Recepción de participantes y entrega de material.',
      'openingSession': 'Ceremonia de apertura',
      'openingSessionDesc': 'Palabras del Director General e invitados.',
      'roundTable': 'Mesa redonda: Innovación',
      'roundTableDesc': 'Debate sobre nuevas tecnologías en el campus.',
      'lunchBreak': 'Pausa para el almuerzo',
      'lunchBreakDesc': 'Libre para almorzar.',
      'workshops': 'Talleres prácticos',
      'workshopsDesc': 'Salas temáticas (TI, Agronomía, Administración).',
      'closingSession': 'Clausura',
      'closingSessionDesc': 'Coffee break y networking.',
      'historyTitle': 'Historial',
      'filterAll': 'Todos',
      'filterInProgress': 'En curso',
      'filterCompleted': 'Finalizado',
      'filterAbsent': 'Ausente',
      'searchHint': 'Buscar evento...',
      'statusInProgress': 'En curso',
      'statusCompleted': 'Finalizado',
      'statusAbsent': 'Ausente',
      'detailsTitle': 'Detalles',
      'certificateButton': 'Certificado',
      'completionDate': 'Fecha de finalización:',
      'meetingDocuments': 'Documentos de la reunión',
      'contactHeading': 'Ponte en contacto',
      'contactDescription': 'Estamos aquí para ayudar. Elige una de las formas abajo para hablar con nosotros.',
      'emailLabel': 'Correo',
      'phoneLabel': 'Teléfono',
      'addressLabel': 'Dirección',
      'socialNetworks': 'Redes sociales',
      'faqTitle': 'Preguntas frecuentes',
      'faqChangePasswordQ': '¿Cómo cambio mi contraseña?',
      'faqChangePasswordA': 'Para cambiar tu contraseña, ve a "Editar perfil" y selecciona la opción de seguridad.',
      'faqSeeSchedulesQ': '¿Dónde veo los horarios de clase?',
      'faqSeeSchedulesA': 'Los horarios están disponibles en la pestaña "Horarios" en la pantalla inicial.',
      'faqContactCoordinationQ': '¿Cómo contacto con la coordinación?',
      'faqContactCoordinationA': 'Puedes usar la pantalla "Contáctanos" para encontrar los contactos oficiales.',
      'faqOfflineQ': '¿La app funciona sin conexión?',
      'faqOfflineA': 'Algunas funciones requieren internet, pero el historial de notificaciones puede verse sin conexión.',
      'fillRequiredFields': 'Completa todos los campos obligatorios.',
      'needInstitutionalEmail': 'Debes usar el correo institucional!',
      'login': 'Iniciar sesión',
      'noAccount': '¿No tienes una cuenta?',
      'register': 'Regístrate',
      'academicEmail': 'Correo académico',
      'password': 'Contraseña',
      'rememberLogin': 'Recordar inicio de sesión',
      'confirmPassword': 'Confirmar contraseña',
      'registerAction': 'REGISTRAR',
      'passwordsDontMatch': 'Las contraseñas no coinciden!',
      'createAccount': 'Crear cuenta',
      'emailHelper': 'Ej: usuario@acad.ifma.edu.br',
      'enterFullCode': 'Ingresa el código completo.',
      'accountVerified': 'Cuenta verificada con éxito!',
      'serverConnectionError': 'Error al conectar con el servidor.',
      'verifyEmailTitle': 'Verifica tu correo',
      'codeSentTo': 'Enviamos un código de 6 dígitos a:',
      'verificationButton': 'VERIFICAR CÓDIGO',
      'resendCode': '¿No recibiste el código? Reenviar',
      'resendSoon': 'Función de reenviar pronto!',
      'lastUpdate': 'Última actualización: 27 de diciembre de 2025',
      'privacyIntroTitle': 'Introducción',
      'privacyDataTitle': 'Recopilación de datos',
      'privacyUsageTitle': 'Uso de la información',
      'privacySharingTitle': 'Compartir',
      'privacySecurityTitle': 'Seguridad',
      'privacyIntro': 'Bienvenido a la app FADIR. Tu privacidad es importante para nosotros. Esta Política de Privacidad explica cómo recopilamos, usamos, divulgamos y protegemos tu información.',
      'privacyDataCollection': 'Recopilamos la información que nos proporcionas directamente, como nombre, correo y foto de perfil, para personalizar tu experiencia en la app.',
      'privacyUsage': 'Usamos tu información para proporcionar, mantener y mejorar nuestros servicios, y enviar notificaciones importantes sobre el campus y eventos.',
      'privacySharing': 'No compartimos tu información personal con terceros, excepto cuando lo exige la ley o para proteger nuestros derechos.',
      'privacySecurity': 'Implementamos medidas de seguridad para proteger tus datos contra acceso no autorizado, alteración o destrucción.',
      'privacyFooter': 'FADIR - Campus Caxias',
      'error': 'Error',
      'retry': 'Reintentar',
      'noPublications': 'Aún no hay publicaciones.',
      'justNow': 'Ahora mismo',
      'minutesAgo': 'min atrás',
      'hoursAgo': 'h atrás',
      'daysAgo': 'días atrás',
      'unknownDate': 'Fecha desconocida',
      'logoNotFound': 'Logo no encontrada',
      'defaultUserName': 'Usuario FADIR',
      'createPost': 'Crear publicación',
      'commentsTitle': 'Comentarios',
      'commentsEmptyTitle': 'Aún no hay comentarios',
      'commentsEmptySubtitle': 'Sé el primero en comentar.',
      'commentsListError': 'No se pudieron cargar los comentarios.',
      'commentsRetry': 'Reintentar',
      'fabPost': 'Publicar',
      'fabEdit': 'Editar',
      'createMeetingTitle': 'Crear Nueva Reunión',
      'meetingEditTitle': 'Editar Reunión',
      'meetingGeneralData': 'Datos Generales',
      'meetingName': 'Nombre del Evento',
      'meetingCampus': 'Campus / Lugar',
      'meetingStartDate': 'Fecha de Inicio',
      'meetingEndDate': 'Fecha de Cierre',
      'meetingSchedule': 'Cronograma',
      'meetingAddItem': 'Agregar Ítem',
      'meetingSelectStartFirst': '¡Selecciona la fecha inicial primero!',
      'meetingEndBeforeStart': '¡La fecha de término no puede ser antes del inicio!',
      'meetingAddActivity': '¡Agrega al menos una actividad!',
      'meetingSave': 'GUARDAR REUNIÓN',
      'meetingUpdate': 'ACTUALIZAR DATOS',
      'meetingCreateSuccess': 'Reunión creada con éxito! ✅',
      'meetingUpdateSuccess': 'Reunión actualizada con éxito! ✅',
      'requiredField': 'Obligatorio',
      'publish': 'Publicar',
      'postHint': '¿Qué quieres compartir?',
      'addToPost': 'Agregar al post',
      'addPhoto': 'Agregar foto',
      'takePhoto': 'Tomar foto',
      'publicAudience': 'Público',
      'imageSelectError': 'Error al seleccionar imagen',
      'publishSuccess': 'Publicado con éxito!',
      'publishError': 'Error al publicar',
      'documentAgendaDecember': 'Agenda de la reunión - Diciembre',
      'documentResults2025': 'Presentación de resultados 2025',
      'documentBudget2026': 'Planilla de presupuestos 2026',
      'documentPreviousMinutes': 'Acta de la reunión anterior',
      'documentInternalRegulation': 'Reglamento interno',
      'eventSaoJoaoMeeting': 'Reunión Campus São João dos Patos',
      'eventSaoLuisMeeting': 'Reunión Campus São Luís',
      'eventCodoMeeting': 'Reunión Campus Codó',
      'eventTimonMeeting': 'Reunión Campus Timon',
    },
  };

  static String of(BuildContext context, String key) {
    // Use read (listen: false) so event handlers can fetch strings without attaching a listener
    final locale = Provider.of<LanguageProvider>(context, listen: false).locale;
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

extension AppStringsContext on BuildContext {
  String t(String key) => AppStrings.of(this, key);
}
